name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/5 * * * *"  

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: curl -X GET https://personal-portfolio-09m9.onrender.com
